version: '3.8'
services:
  minecraft:
    build:
      context: .
      dockerfile: dockerfile
    stdin_open: true
    tty: true
    ports:
      - "25565:25565"
    volumes:
      - minecraft-data:/server/server/world
volumes:
  minecraft-data:
